Update
kyutech-programming-club/linebot-workspace pull request #2
Opened 2019-04-03 14:05 UTC by rkdora

- サンプルコードの追加
- サンプル画像の差し替え

2019-04-03 14:15 UTC, rkdora commented
@tanacchi 
sample4.jsを使うにあたって、たなっちは以下の設定が必要と思われます。

![image](https://user-images.githubusercontent.com/20394831/55485693-e67abd80-5665-11e9-901f-b1b6a5406d09.png)
![image](https://user-images.githubusercontent.com/20394831/55485719-f4304300-5665-11e9-8cb6-940f82ed88bf.png)
![image](https://user-images.githubusercontent.com/20394831/55485742-001c0500-5666-11e9-86b3-983d1c21ab86.png)

2019-04-03 14:35 UTC, tanacchi requested changes
THX

2019-04-03 14:35 UTC, tanacchi commented on sample2.js
> +server.post("/webhook", line.middleware(lineConfig), (req, res) => {
見たサンプルが違うから俺が追加した `app.js` と POST 先のURLが異なるものになってる。
不要なミスを避けるために俺はルート（"/"）にしたけど、どっちにするかは任せます。
どちらにせよ統一してください
他のサンプルがも同様

2019-04-03 14:39 UTC, tanacchi commented on sample2.js
> +server.post("/webhook", line.middleware(lineConfig), (req, res) => {
「POST 先の URL」っていう言い方が正しいかはびみょいです。
勉強します。

2019-04-03 14:56 UTC, rkdora commented
ありがとう。気づかんかった。（動作確認サボってました(*_*;）
なんとなく、webhookを使う方に統一してみました。（今度はちゃんと動作確認済み）
理由としては、webhook送信を有効にしてたりしてるので正しそう・・・？
おいらも勉強しときます。

2019-04-03 17:36 UTC, tanacchi commented
> なんとなく、webhookを使う方に統一してみました。（今度はちゃんと動作確認済み）
> 理由としては、webhook送信を有効にしてたりしてるので正しそう・・・？

ここを変えることによって「Bot サイドがサーバー送るリクエスト先」が変わります（多分）
つまり LINE 側の設定もいじらないと動かないぞ

2019-04-03 17:37 UTC, tanacchi approved these changes
OK People

2019-04-04 04:08 UTC, rkdora commented
> > なんとなく、webhookを使う方に統一してみました。（今度はちゃんと動作確認済み）
> > 理由としては、webhook送信を有効にしてたりしてるので正しそう・・・？
> 
> ここを変えることによって「Bot サイドがサーバー送るリクエスト先」が変わります（多分）
> つまり LINE 側の設定もいじらないと動かないぞ

![image](https://user-images.githubusercontent.com/20394831/55529128-abff3800-56da-11e9-88b8-ab846ac780a7.png)

2019-04-04 04:08 UTC, merged